### PR TITLE
fix build because of missing preval

### PR DESCRIPTION
**Pull request by kalimantos**
solves issue #3

### CODE REVIEW

**Comment by kalimantos** [comment]
Installing styled-components with old package.json configuration `"styled-components": "^3.3.3"`, currently installs the 3.4.10 version that has `src` folder instead of `lib`.
So i've updated the version inside package.json and changed the styled-components reference using src

**Comment by diegomura** [comment]
Thanks for addressing this. We recently merged a PR where we changed loading the lib from `src` to `lib` (check [here](https://github.com/react-pdf/styled-components/pull/2)).

What's the preval for here?

**Comment by kalimantos** [comment]
Sorry about my bad explaination. I try to explain what i found/what i did again better (i hope 😄).
When i gave the error of the issue #3 i tried to rebuild this by myself.
I forked this repo and npm installed, i runned npm run build and tried to use that compiled in my application.
It didn't worked because of 2 problems:
1. the styled-components version installed was `3.4.10` that has no `lib` folder, but instead has a `src` folder.
2. styled-components@3.4.10 uses `preval` to generate error messages on compile time and needs to be compiled using `babel-plugin-preval`. [here](https://github.com/styled-components/styled-components/blob/v3.4.10/src/utils/error.js#L10)

For this 2 problems i made 3 changes:
- add `babel-plugin-preval` into rollup build script [here](https://github.com/react-pdf/styled-components/pull/4/files#diff-ff6e5f22a9c7e66987b19c0199636480R37)
- fix `styled-components` version to `3.4.10` [here](https://github.com/react-pdf/styled-components/pull/4/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R39)
- change styled-components references from `lib` to `src` [here](https://github.com/react-pdf/styled-components/pull/4/files#diff-168726dbe96b3ce427e7fedce31bb0bcR3)

Thanks for the quick answer. I hope this could help.

**Comment by diegomura** [comment]
Thanks for the explanation! An what if someone is using styled-components < 3.4.10 ? It should work exactly the same right? (`/src' folder always present)

**Comment by kalimantos** [comment]
I've tried right now to use `3.3.3`, folder `src` is still present and folder `lib` is now present. But the same error of #3 still occurr.

**Comment by diegomura** [comment]
@kalimantos that means this fix should work for all SC versions?

**Comment by diegomura** [comment]
If that’s so I promise I’ll merge and publish this today! Sorry for taking that long

**Comment by kalimantos** [comment]
It uses the 3.4.10, so `@react-pdf/styled-components` will use 3.4.10 styled-components. It doesn't matter what styled-components version you're using in the same project that uses `@react-pdf/styled-components`. Also there's no breaking changes between 3.3.3 and 3.4.10 ([can check here](https://github.com/styled-components/styled-components/blob/master/CHANGELOG.md))

**Pull request merged**
